// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wagner_DAmaral_Assignment01.Models;

namespace Wagner_DAmaral_Assignment01.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181120205836_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wagner_DAmaral_Assignment01.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(140);

                    b.Property<string>("Ingredients")
                        .IsRequired();

                    b.Property<string>("PictureUrl")
                        .IsRequired();

                    b.Property<string>("PrepareMode")
                        .IsRequired();

                    b.Property<int>("Rating");

                    b.Property<string>("RecipeName")
                        .IsRequired();

                    b.Property<int>("TimeToPrepare");

                    b.HasKey("RecipeID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Wagner_DAmaral_Assignment01.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int?>("RecipeID");

                    b.Property<double>("Stars");

                    b.HasKey("ReviewID");

                    b.HasIndex("RecipeID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Wagner_DAmaral_Assignment01.Models.Review", b =>
                {
                    b.HasOne("Wagner_DAmaral_Assignment01.Models.Recipe", "Recipe")
                        .WithMany("Reviews")
                        .HasForeignKey("RecipeID");
                });
#pragma warning restore 612, 618
        }
    }
}
